### ISSUE TITLE
Data Requirements and error

### ISSUE THREAD

**Issue by Arthur-Langlois** [Daniel-Pailanir/sdid#25]
Hi, I am just confused as to what are the different data format requirements, specifically, what is supposed to be ```T``` ? Where do we input the time of treatment ? I passed my ```Year``` variable, to T and as I expected I received an error ```repeated time values within panel```

```
sdid CrudeRate State Year Treated, vce(placebo) reps(50)
```

**Comment by Arthur-Langlois** [comment]
Hi Daniel, thank you for your response. I am running into a different issue. After inputing the following code: 
```sdid cruderate state year after_treatment vce(bootstrap) reps(50)``` I get the following error: ```factor-variable and time-series operators not allowed```. My data looks as follows:
![Screen Shot 2022-04-18 at 23 40 30](https://user-images.githubusercontent.com/56982634/163915631-67a887c6-827c-41e5-9068-b101b58b09b5.png)

Am I using the right data format ?

**Comment by damiancclarke** [comment]
Hi Arthur,
I believe there is a missing comma following `after_treatment` and before `vce(bootstrap)`. If you add the comma, all should be fine.
Best wishes,
Damian
