### ISSUE TITLE
variable *timevar* not found

### ISSUE THREAD

**Issue by gj330** [Daniel-Pailanir/sdid#29]
Hi. I am using it in the staggered adoption setting. My timevar is called _time_. After a few iterations, I got an issue like this:
![Screen Shot 2022-05-13 at 16 07 03](https://user-images.githubusercontent.com/32436379/168302112-c9edc40c-f2e8-4f1e-946a-7f58fc35888b.png)

_variable time not found_

I am not sure where it goes wrong.

Can anyone help me? thank you

**Comment by Daniel-Pailanir** [comment]
Hi @guohui-jiang, that problem has a solution mentioned above [graph error](https://github.com/Daniel-Pailanir/sdid/issues/26), but the best way to solve this is to reinstall sdid using the github version, because we fixed the bug in the main code.

**Comment by guohui-jiang** [comment]
thank you, Daniel!
