### ISSUE TITLE
May I ask whether based on the code to get the weight value and identifiers of controls?

### ISSUE THREAD

**Issue by ericywon** [Daniel-Pailanir/sdid#41]
Sorry to bother you but I am now using this command to do the test. May I ask whether based on the code to get the weight value and identifiers of controls?

**Comment by Daniel-Pailanir** [comment]
Hi, I'm not sure what you mean. Do you mean lambda and omega weight? or the betas that are associated with the covariates?

**Comment by ericywon** [comment]
Dear Daniel,

Thanks a lot for your reply. So my question is could I directly get the
lambda and omega weights from the command?

Thank you again.

Daniel Pailañir ***@***.***> 于2022年10月15日周六 23:32写道：

**Comment by Daniel-Pailanir** [comment]
Of course, this is stored in two matrix after the estimation. To access, you can view both matrices using ```matlist e(lambda)``` and ```matlist e(omega)```, or create new matrix from them, for example ```matrix lambda=e(lambda)```.

**Comment by ericywon** [comment]
Dear Daniel,

Many thanks this is very helpful! Let me try that.

Daniel Pailañir ***@***.***> 于2022年10月17日周一 20:23写道：
