### ISSUE TITLE
method() option in command

### ISSUE THREAD

**Issue by brianfabre** [Daniel-Pailanir/sdid#42]
In the readme, it shows the allowance of the method() command to choose between sdid, did, and sc. When running the command however it seems like this is not allowed. In 'help sdid' it also has no mention of this. I am guessing that this function is not present at the moment, correct?

**Comment by Daniel-Pailanir** [comment]
Hi, the ```method()``` option is only available in the recent version of ```sdid```. Reinstall ```sdid``` using ```net install sdid, replace from("https://raw.githubusercontent.com/daniel-pailanir/sdid/master")``` and the option will be available. The help will be updated soon.

**Comment by brianfabre** [comment]
It works. Thank you!
