### ISSUE TITLE
Graphs in Staggered Adoption

### ISSUE THREAD

**Issue by mldoucette1** [Daniel-Pailanir/sdid#46]
Hello Daniel,

Thanks again for your quick response related to the SE in the e(tau) matrix, it was very helpful. 

I have another question and appreciate your time. In the setting of staggered treatment adoption, is there a way to get 1 graph for both the trend line and/or the state weights? I tried combining the treatment cohorts using the e(difference) and e(series) matrices. Do they need to be weighted by treatment cohort length * size? Any thoughts would be very helpful.

Thanks,

Mitch Doucette
mdoucet3@jhu.edu

**Comment by damiancclarke** [comment]
Hi Mitch,

If you want to do some non-standard graphical processing, we have laid out some examples about how to do this in a new working paper, here: [https://docs.iza.org/dp15907.pdf](https://docs.iza.org/dp15907.pdf). On pages 19-20, and appendix 2 we show how the graphs that are automatically exported can be made using the ereturned elements, so hopefully with this you can further edit graphs as you need!

Best wishes,
Damian
