### ISSUE TITLE
sdid with multiple treated units

### ISSUE THREAD

**Issue by Emildvd** [Daniel-Pailanir/sdid#52]
Dear all,

When running the sdid (Synthetic DiD) command in Stata with multiple treated units (at one point in time) and specifying the method to be synthetic control method; method(sc), Stata simply averages the outcome variable for all treated units it seems. On Stata, it states that the command is built on Abadie et al., (2010), however, in their paper they write that "The synthetic control framework can easily accommodate estimation with multiple treated units by fitting separate synthetic controls for each of the treated units".

My question is, therefore, what does the method actually do with multiple treated units? And where can I see how it mathematically differs from the case of a single adopted treatment? - also for the sdid case?

Best,
Emil

**Comment by damiancclarke** [comment]
Hi Emil,

Apologies for not having responded here previously!  What sdid does with synthetic control in terms of aggregation is the same that it does with synthetic diff in diff.  For each time period it calculates a single (different) synthetic control, and then calculates the time-specific effect tau_a (where a indexes adoption periods).  Then, to generate a single treatment effect, these are simply aggregated, and given weights according to their number of post-treatment periods.  If you would like to see the precise formula, I would refer you to equation (8) of the synthetic difference in differences paper forthcoming in the Stata Journal (https://www.damianclarke.net/research/papers/SDID.pdf).  Kind regards,
Damian
