### ISSUE TITLE
Issues with folders and spaces

### ISSUE THREAD

**Issue by marcos-lee** [Daniel-Pailanir/sdid#55]
In Windows, if your TEMP directory contains spaces, using the -graph- option throws an error. This is a "common" error in Stata packages and the fix is to encase every tempfile command in the .ado with quotes, or change your TEMP environment variable. Whether this warrants a fix on the developer side or a note on the package help file or github page is up to the developer.

**Comment by damiancclarke** [comment]
Hi Marcos, Thanks for letting us know.  I think that this should be corrected now.  If you would like to check the version of the ado that is now available for download from github, hopefully it should support tempfiles even if there are spaces in directory names.  Best wishes.  Damian
