### ISSUE TITLE
Application to triple difference

### ISSUE THREAD

**Issue by diosas17** [Daniel-Pailanir/sdid#58]
Dear all,

First of all, thank you for developing wonderful command. It is really helpful.

I would like to ask regarding applying sdid to triple difference (DDD) setting.
I am considering utilizing triple difference; timing, treatment (varying across states), and group (varied exposure to treatment). In the meantime, it would be great if I could have synthetic control approach for valid identification as in your command. In this regard, I am thinking following way to apply sdid.

First, I define the treatment dummy as the interaction of indicators of post-periods, treated state, and treated group.
Second, I include all the other differences in the covariates ( each indicator and the interaction of each pair of indicators ).
Then, the command would be 

_sdid outcome group year post*(treated state)*(treated group), vce(bootstrap) covariates(post (treated state) (treated group) post*(treated state) post*(treated group) (treated state)*(treated group))_

Could you please tell me whether this would be an appropriate approach?

I appreciate your consideration and hope you have a great day!
Sincerely,
Woosuk

**Comment by damiancclarke** [comment]
Dear Woosuk,

I'm really sorry for the very long delay in replying here!  I'm not sure if this will necessarily get at what you're after given that the covariates are concentrated out in a pre-matching step, and so will not set up a synthetic DDD framework, but rather will do synthetic DD with the variable having concentrated out (full) state and time trends.  Perhaps a simpler way would be to *first* generate a double difference for each unit, and then use this differenced variable to run SDID?  For example, if you take outcome for treated group=1 and substract the outcome for treated group = 0 (working at the state and time level), you could then use this differenced variable, and it is more likely what you're after with a triple difference.

Hopefully this is still useful for you...
Best wishes,
Damian
