### ISSUE TITLE
Event study PLot

### ISSUE THREAD

**Issue by anzonyquispe** [Daniel-Pailanir/sdid#60]
Is it possible to construct event study plots for staggered treatment?

**Comment by damiancclarke** [comment]
Hello @anzonyquispe,

You would need to have some theory related to how you might group lags and leads to the policy if you wish to do event studies based on SDID (I presume you are referring to the event studies in the working paper).  You could certainly do an event study for each adoption and present them separately, but would need to have some particular way to aggregate them (perhaps the methods discussed in [Sun & Abraham](https://www.sciencedirect.com/science/article/pii/S030440762030378X), equation 28 could be an option).  However, I unfortunately do not think there is theory yet that shows this is valid in the SDID setting.
Best wishes,
Damian
