### ISSUE TITLE
Inconsistencies in `e(series)` and `e(difference)` Matrices

### ISSUE THREAD

**Issue by xklong1202** [Daniel-Pailanir/sdid#62]
Hi all,

Thank you so much for developing this valuable `sdid` command! I have a question regarding a discrepancy in the output matrices `e(series)` and `e(difference)`. According to the documentation, the difference between the control and treatment series should be equal to `e(difference)`, but I am encountering inconsistent results. As shown in the picture, columns D and H are different, even though they should be the same.

<img width="478" alt="Screenshot 2023-12-30 at 8 55 36 PM" src="https://github.com/Daniel-Pailanir/sdid/assets/155174492/10c9de63-e68d-44be-93b6-a98d9eaacfa0">

I have tried the quota example, and it yielded consistent results. However, I am observing inconsistencies in the results for each individual SDID model in my dataset.

Once again, I appreciate your work on this command and would be grateful for any insights or assistance in resolving this matter.

Best,
Lydia

**Comment by damiancclarke** [comment]
Hi Lydia,

Thanks a lot for reporting this.  Do you have a minimum working example which shows this behaviour which you 
would be able to share with us?  As you say, in the staggered adoption setting with quotas things look correct, and we haven't seen this behaviour elsewhere.  Though the above output clearly appears inconsistent in the series.  If you have an example that we can work with, we are happy to look into this.  

Thanks v much,
Damian

**Comment by xklong1202** [comment]
Hi Damian,

Thank you for your prompt response! I appreciate your willingness to look into the issue.

I will prepare a minimum working example that demonstrates the behavior and send it to you via email shortly.

Best,
Lydia

**Comment by damiancclarke** [comment]
Dear Lydia,

Thank you very much for reporting this and providing the example by email.  I am just confirming that this bug is now fixed, and am closing this issue now.  Thank you again very much for reporting this!
