### ISSUE TITLE
matsize limitations

### ISSUE THREAD

**Issue by nathalieluck** [Daniel-Pailanir/sdid#87]
Hi, 

thank you very much for developing this code.

I am trying to implement it with my dataset but keep running into issues with matsize.
The dataset is quite large (28,647 village units, observed across 8 years). However, when browsing the resolved issues, I also saw another user describe a dataset with 100,000 observations (I am assuming this means 100,000 units). 

Specifically, I ran the following command: 
sdid outcome village_ID year treatment  , vce(bootstrap) 

However, stata reported the following error: matsize too small to create a [23473,1] matrix

Would you have any  advice how I can circumvent the matsize issue with the sdid command? I am also a bit confused where the 23473 comes from, does it mean that not all controls where used for the matching and some dropped?

Just in case I have also attached the dataset, 
[sdid_reduced_dataset.csv](https://github.com/user-attachments/files/17449862/sdid_reduced_dataset.csv)

I would be very grateful in case you have any advice. 

Thank you very much in advance, 
Nathalie

**Comment by nathalieluck** [comment]
Actually it was due to my Stata Version (with Stata 17 it works).

**Comment by damiancclarke** [comment]
Thanks very much @nathalieluck for writing and updating this thread, and I'm really sorry we hadn't managed to get to it yet (deep in semester on my side, and things are inevitably a fair bit slower).  It's great to know that moving to Stata 17 resolved this (or perhaps it was a move from Stata SE to Stata MP or similar?).  It's good for others to know that in Stata 16 some issues with matrix size may come up.  Presumably you had already played around with `set matsize`, though I will leave this note here in case anyone else comes to this in the future, as it may be a quick solution if the data are large, but still within Stata's [limits](https://www.stata.com/products/detailed-size-limits/), as one could try something like `set matsize 50000` (or some desired value within limits) to permit large matrices.   Thanks again for the update Nathalie.
